### ISSUE TITLE
SSL süreniz dolmuş

### ISSUE THREAD

**Issue by duman** [trkodlama/makaleler#1]
Gezerken denk geldim.

```
Your connection is not private

Attackers might be trying to steal your information from www.trkodlama.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
```

SSL Analyzer sonucu: https://sslanalyzer.comodoca.com/?url=https%3A%2F%2Fwww.trkodlama.com%2F

* Tue, 31 Oct 2017 23:59:59 GMT     Expired 7 days ago! *

Yenilemeyi unuttunuz sanıyorum. İyi günler.

**Comment by oralunal** [comment]
Evet, farketmemişim. Uzun süredir ilgilenemiyorum yoğunluğumdan ötürü. Teşekkürler ilginiz için.. Şimdilik SSL'i devre dışı bırakıyorum.
